export const SET_FILTER = 'SET_FILTER';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_DRINKS = 'SET_DRINKS';
export const LOADING = 'LOADING';
export const FILTER_BY_SEARCH = 'FILTER_BY_SEARCH';
export const INCREMENT_PAGENUMBER = 'INCREMENT_PAGENUMBER';
export const DECREMENT_PAGENUMBER = 'DECREMENT_PAGENUMBER';





